# Generate a new component
component:
  # All paths are relative to src folder
  temples:
    # Component entry point file
    - template: component.template
      output: "components/{{ name }}/index.js"
      default:
          name: Component

    # Component CSS stylesheet
    - output: "components/{{ name }}/styles.css"

    # Component test file
    - template: test.template
      output: "components/{{ name }}/test.js"

container:
  base: .
