Gatsby-Template:
  base: ./test
  prompt:
    - name
  temples:
    - template: component.template
      output: "components/{{ name }}/index.js"

React-Component:
  base: ./test
  prompt:
    - name
  temples:
    - template: component.template
      output: "components/{{ name }}/index.js"

    # Component CSS stylesheet
    - template: styles.template
      output: "components/{{ name }}/styles.css"

    # Component test file
    - template: test.template
      output: "components/{{ name }}/test.js"

