base:
  templates: .temples/templates/files
  target:
    files: src/files
    inserts: src/inserts

inserts:
  regex:
    js: '\/\/ temples: (.+)'
    md: '^# temples: (.+)'
  before: ', '
  after: '/n'
  position: below

default:
  var_a: 'a'
  var_b: 'b'

handlebars: HandlebarsConfig.js
verbose: true

generators:
  component:
    base: .temples/components
    prompt: [name, title]
    default:
      var_c: 'c'
    files:
      - template: component.hbs
        target: target.js
    inserts:
      - template: insert.hbs
        target: components/index.js
        regex: ...
        before: ...
        after: ...
        position: ...
