# Define base paths to find templates
# and produce output files.
base:
  # Template sources for files and inserts.
  templates: .temples/templates/files

  # Produced files and inserts.
  target:
    files: src/files
    inserts: src/inserts

# File that overrides handlebars instance.
handlebars: HandlebarsConfig.js

# Regex to match temples inserts
# based on file extensions.
regex:
  js: '\/\/ temples: (.+)'
  md: '^# temples: (.+)'

# Where to insert relative to regex
#   above: above the regex
#   below: under the regex
#   left: left of the regex
#   right: right of the regex
position: below

# Default key value mapping.
default:
  var_a: 'a'
  var_b: 'b'

# Log out processes
verbose: true

generators:
  component:
    base: .temples/components
    prompt: [name, title]
    regex: ...
    position: ...

    default:
      var_c: 'c'

    files:
      - template: component.hbs
        target: target.js

    inserts:
      - target: components/index.js
        regex: ...
        position: ...
